version: 2.1

orbs:
  android: circleci/android@2.1.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.06
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - gradle-deps-v1
      - run:
          name: Grant execute permission for Gradlew
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: gradle-deps-v1
          paths:
            - ~/.gradle
      - run:
          name: Build Project
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks
      - run:
          name: Run Lint and Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
